apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.privilege.name }}
  labels: 
    owner: d
spec:
  replicas: {{ .Values.privilege.replicas }}
  
  selector:
    matchLabels:
      project: {{ .Values.privilege.name }}
   
  template:
    metadata:
      labels:
        project: {{ .Values.privilege.name }}
     
    spec:
      containers:
        - name: rsoigateway
          image: {{ .Values.privilege.image }}
          ports:
            - containerPort: {{ .Values.privilege.containerPort }}