apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: ingress

spec:
  rules:
  - host:
    http:
      path:
        - backend:
          serviceName: rsoigateway
          servicePort: 8080