apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.gateway.name }}
  labels:
    owner: a
    
spec:
  type: LoadBalancer
  selector:
    app: {{ .Values.gateway.name }}
    ports:
      - name: {{ .Values.gateway.name }}-listener
        proticol: TCP
        port: 80
        targetPort: {{ .Values.gateway.containerPort }}