apiVersion: v1
kind: Service
metadata: 
  name: {{ .Values.gateway.name }}
  labels:
    owner: a
    
spec:
  selector:
    app: {{ .Values.gateway.name }}
  ports:
    - name: {{ .Values.gateway.name }}-listener
      protocol: TCP
      port: {{ .Values.gateway.containerPort }}
      targetPort: {{ .Values.gateway.containerPort }}
  type: LoadBalancer