name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

          - name: Docker step
            run: |
              echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_LOGIN }} --password-stdin

          - name: K8S step
            run: |
              curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
              exec -l $SHELL
              echo ${{ secrets.YANDEX_TOKEN }} | yc init --password-stdin  
              yc managed-kubernetes cluster get-credentials --id ${{ secrets.CLUSTER_ID }} --external --force
              helm install lab k8s\
              kubectl get pods
              kubectl get svc
              kubectl get ingress
            timeout-minutes: 1

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: <variant>/postman/collection.json
          environment: <variant>/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"